guides/tutorials/agent-config.md
guides/tutorials/issue-a-credential.md
sidebars.js

- Fixes most of the feedback that @TimoGlastra left on the previous PR
- I will create a new PR after this is merged with the updated code snippets
**IMPORTANT**
The code snippets are incorrect and with the next PR these will be extracted and fixed.

docs(tutorial): PR fixes for issue credential

---

.gitignore
guides/tutorials/agent-config.md

from: https://discord.com/channels/905194001349627914/941708033434738768/986454659805904947

fix(config): raw key fix mistake

---

guides/tutorials/agent-config.md

Signed-off-by: Moriarty <moritz@animo.id>

feat: add docs for specifying taa accept mechanism

---

guides/updating/versions/0.1-to-0.2.md

fix: typo in update document

---

docusaurus.config.js

chore: update links after transfer

---

snippets/package.json
snippets/src/issue-a-credential.ts
snippets/src/set-up-rn.ts
snippets/src/set-up.ts

- Fixes https://github.com/hyperledger/aries-framework-javascript/issues/912
- Adds RN snippet
Signed-off-by: Berend Sliedrecht <berend@animo.id>

feat(setup): snippified

---

guides/getting-started/set-up/index.md

Fixes #47 
Fixes https://github.com/hyperledger/aries-framework-javascript/issues/916

fix: add indy-sdk-react-native dep

---

guides/tutorials/agent-config/index.md

Signed-off-by: Akias <namhainguyenminh@gmail.com>

fix: spelling correction

---

guides/tutorials/postgres-database-nodejs/index.md
guides/tutorials/postgres-database-nodejs/windows.md
sidebars.js

Signed-off-by: Sai Ranjit Tummalapalli <sairanjit.tummalapalli@ayanworks.com>

docs: postgres plugin for nodejs on windows

---

CONTRIBUTING.md
guides/ecosystem/index.md

See https://github.com/hyperledger/aries-javascript-docs/issues/51

docs: ecosystem contributing links

---

.github/ISSUE_TEMPLATE/documentation-request.yml

chore: add documentation request form

---

guides/getting-started/installation/react-native/ios.md

Signed-off-by: Moriarty <moritz@animo.id>

fix(ios): update ios installation for react-native

---

guides/getting-started/set-up/index.md

fix: import http inbound from node package

---

guides/ecosystem/bifold.md
guides/ecosystem/extensions.md
guides/ecosystem/framework.md
guides/ecosystem/index.md
guides/extensions/index.md
sidebars.js

Signed-off-by: Jim Ezesinachi <ezesinachijim@gmail.com>

feat: added basic extensions repo documentation

---

sidebars.js

fix: add 0.3 migration guide to sidebar

---

guides/tutorials/agent-config/index.md
guides/tutorials/issue-a-credential.md
snippets/src/issue-a-credential.ts

Also document changes for https://github.com/hyperledger/aries-framework-javascript/issues/1072
This for v0.3.0 onward
related to [this issue 1072](https://github.com/hyperledger/aries-framework-javascript/issues/1072)
tests fail obviously because this need AFJ>=0.3.0
Signed-off-by: Moriarty <moritz@animo.id>

feat: document indyNamespace for ledger config

---

guides/updating/versions/0.2-to-0.3.md

Signed-off-by: Ariel Gentile <gentilester@gmail.com>

feat: changes in connections, dids and handlers to 0.2-0.3 migration guide

---

guides/getting-started/set-up/index.md
guides/tutorials/postgres-database-nodejs/index.md
guides/updating/update-assistant.md

fix: agent setup for 0.3.0

---

guides/getting-started/set-up/index.md

fix: android setup

---

docusaurus.config.js

Signed-off-by: Jim Ezesinachi <jim@animo.id>

fix: concepts-and-tutorials-links-not-working

---

guides/updating/update-indy-sdk-to-askar.md
sidebars.js

Signed-off-by: blu3beri <blu3beri@proton.me>

docs: added indy-sdk to aries askar migration docs

---

versioned_docs/version-0.3/getting-started/set-up/index.md

HttpOutboundTransport and HttpInboundTransport  missing in full code Snippet

fix: add missing transports

---

guides/getting-started/set-up/index.md

The two links to askar and indy storage setup 404'd currently, corrected them so they point to the right location like the links immediately below them work.

fix: corrected two links

---

guides/getting-started/index.md
versioned_docs/version-0.4/getting-started/index.md

Hi guys. While I was looking at the credo docs, there was a broken link, so I fixed it. :)
The broken link was in 0.4 and the latest.
This is my first time contributing this repo. I'm open to change.
Let me know if anything needs to be changed.
Thank you

doc: fix broken Agent setup link
